services:
  app:
    build: .
    ports:
      - "8050:8050"
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - ./spotidash:/app/spotidash
